# Generated by Django 3.1.1 on 2022-06-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_auto_20220621_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproductomodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
