# Generated by Django 3.2.12 on 2022-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosmodel',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
