# Generated by Django 3.1.1 on 2022-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0002_alter_serviciosmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
