# Generated by Django 3.2.12 on 2022-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
